/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install. It is included here so
// the scaffold is complete before dependencies are installed.
